sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="stable"
    - DOCKERFILE="mainline"

before_script:
  - docker version

script:
  - docker build -t ${DOCKERFILE} ./${DOCKERFILE}

after_script:
  - docker images
