sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="Dockerfile-stable" DOCKERPATH="stable"
    - DOCKERFILE="Dockerfile-stable-alpine" DOCKERPATH="stable"
    - DOCKERFILE="Dockerfile-mainline" DOCKERPATH="mainline"
    - DOCKERFILE="Dockerfile-mainline-alpine" DOCKERPATH="mainline"

before_script:
  - docker version

script:
  - docker build -f ./${DOCKERPATH}/${DOCKERFILE} -t ${DOCKERPATH} ./${DOCKERPATH}

after_script:
  - docker images
