sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="Dockerfile" DOCKERPATH="1.12"
    - DOCKERFILE="Dockerfile" DOCKERPATH="1.13"

before_script:
  - docker version

script:
  - docker build -f ./${DOCKERPATH}/${DOCKERFILE} -t ${DOCKERPATH} ./${DOCKERPATH}

after_script:
  - docker images
